### ISSUE TITLE
Succesful datapackage casts now error when publishing

### ISSUE THREAD

**Issue by givadis** [openspending/datapackage-pipelines-fiscal#11]
In order to submit an issue, please ensure you can check the following. Thanks!

* [ ] Declare which version of Python you are using (`python --version`)
* [ ] Declare which operating system you are using

I have a [working example ](https://openspending.org/viewer/da45ca548f2174321bc5e28a83933711:v1.0?measure=%22Betrag.sum%22&groups%5B%5D=%22administrative_classification_2.Funktion_Nr_Name%22&order=%22Betrag.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en)of my fiscal data on openspending (data is linked at the end of the page):

When I try to reload the cvs I get now an error:

dump.to_path
ERROR   :Failed to cast row {'id': 1}
ERROR   :1) Field "id" can't cast value "1" for type "string" with format "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 93, in schema_validator
    schema.cast_row(to_cast)
  File "/usr/local/lib/python3.6/site-packages/tableschema/schema.py", line 152, in cast_row
    raise exceptions.CastError(message, errors=errors)
tableschema.exceptions.CastError: There are 1 cast errors (see exception.errors)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/dump/to_path.py", line 31, in <module>
    PathDumper()()
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 47, in __call__
    finalizer=self.finalize
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 69, in spew
    for rec in res:
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 122, in row_counter
    for row in resource:
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 251, in rows_processor
    for row in resource:
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 98, in schema_validator
    raise ValueError(row) from e
ValueError: {'id': 1}

**Comment by akariv** [comment]
Hey @givadis,

Which version of `datapackage-pipelines-fiscal` are you using?
Can you share your `fiscal.source-spec.yaml` file?

**Comment by givadis** [comment]
Hi @akariv I am using the official packager from openspending.org. As far as I know this is kind of a black box and I don't have the information you ask for. At least I haven't seen anything like that in my workspace.
